"""Convert raw financial metrics into normalized category and overall scores."""

from .config import (
    DEFAULT_SCORING_PROFILE,
    MINIMUM_CATEGORIES,
    MINIMUM_COVERAGE_PERCENT,
    SCORE_VERSION,
)
from .metrics import format_metric, valid_number

ANCHOR_QUALITY = {"poor": 0.0, "acceptable": 0.4, "good": 0.7, "excellent": 1.0}

METRIC_EXPLANATIONS = {
    "roic": "Measures after-tax operating profit generated by invested debt and equity capital.",
    "return_on_capital": "Measures operating profit generated from capital employed in the business.",
    "return_on_equity": "Measures net income generated from average positive shareholder equity.",
    "gross_margin": "Measures gross profit retained from revenue before operating expenses.",
    "operating_margin": "Measures operating profitability after core business expenses.",
    "net_margin": "Measures bottom-line profit retained from revenue.",
    "revenue_growth": "Measures the year-over-year direction of company revenue.",
    "eps_growth": "Measures the year-over-year direction of earnings per share.",
    "free_cash_flow_growth": "Measures improvement or deterioration in free cash flow.",
    "operating_income_growth": "Measures improvement or deterioration in operating income.",
    "debt_to_equity": "Measures debt relative to shareholder equity.",
    "current_ratio": "Measures short-term assets available to cover short-term obligations.",
    "interest_coverage": "Measures operating earnings available to cover interest expense.",
    "net_debt_to_ebitda": "Measures net leverage relative to operating earnings.",
    "free_cash_flow": "Checks whether the business currently generates positive free cash flow.",
    "operating_cash_flow_to_net_income": "Measures whether reported earnings are supported by operating cash flow.",
    "free_cash_flow_margin": "Measures free cash flow generated from each dollar of revenue.",
    "positive_cash_flow_consistency": "Measures how consistently recent annual free cash flow has remained positive.",
    "operating_cash_flow_margin": "Measures operating cash flow generated from each dollar of revenue.",
}

CALCULATION_METHODS = {
    "roic": "nopat_over_average_invested_capital",
    "return_on_capital": "ebit_over_capital_employed",
    "return_on_equity": "net_income_over_average_shareholders_equity",
    "gross_margin": "gross_profit_over_revenue",
    "operating_income_growth": "sign_aware_period_growth",
    "operating_cash_flow_margin": "operating_cash_flow_over_revenue",
}


def score_label(score):
    if score >= 85:
        return "Excellent"
    if score >= 70:
        return "Strong"
    if score >= 55:
        return "Fair"
    if score >= 40:
        return "Weak"
    return "Poor"


def _piecewise_quality(value, thresholds, direction):
    value = valid_number(value)
    if value is None:
        return None
    ordered_names = ("poor", "acceptable", "good", "excellent")
    anchors = [(thresholds[name], ANCHOR_QUALITY[name]) for name in ordered_names]
    if direction == "lower":
        anchors = sorted(anchors, key=lambda item: item[0])
    if value <= anchors[0][0]:
        return anchors[0][1]
    if value >= anchors[-1][0]:
        return anchors[-1][1]
    for (left_value, left_quality), (right_value, right_quality) in zip(anchors, anchors[1:]):
        if left_value <= value <= right_value:
            position = (value - left_value) / (right_value - left_value)
            return left_quality + position * (right_quality - left_quality)
    return None


def score_higher_is_better(value, poor, acceptable, good, excellent, max_points):
    quality = _piecewise_quality(
        value,
        {"poor": poor, "acceptable": acceptable, "good": good, "excellent": excellent},
        "higher",
    )
    return None if quality is None else max(0.0, min(float(max_points), quality * max_points))


def score_lower_is_better(value, excellent, good, acceptable, poor, max_points):
    quality = _piecewise_quality(
        value,
        {"excellent": excellent, "good": good, "acceptable": acceptable, "poor": poor},
        "lower",
    )
    return None if quality is None else max(0.0, min(float(max_points), quality * max_points))


def _metric_points(value, settings):
    value = valid_number(value)
    if value is None:
        return None
    if settings["direction"] == "positive":
        return float(settings["weight"]) if value > 0 else 0.0
    thresholds = settings["thresholds"]
    if settings["direction"] == "lower":
        return score_lower_is_better(value, max_points=settings["weight"], **thresholds)
    return score_higher_is_better(value, max_points=settings["weight"], **thresholds)


def _reference(settings):
    if settings["direction"] == "positive":
        return "Positive values receive full credit"
    thresholds = settings["thresholds"]
    unit = "%" if settings["unit"] == "percent" else "x"
    scale = 100 if unit == "%" else 1
    values = ", ".join(f"{name} {value * scale:g}{unit}" for name, value in thresholds.items())
    prefix = "Lower is stronger; " if settings["direction"] == "lower" else ""
    return f"{prefix}anchors: {values}"


def score_financial_metrics(metrics, profile=None):
    profile = profile or DEFAULT_SCORING_PROFILE
    categories = {}
    available_weight = 0
    available_metric_count = 0
    expected_metric_count = 0
    available_categories = 0
    normalized_category_points = 0.0
    available_category_weight = 0

    for category, category_settings in profile.items():
        max_score = category_settings["weight"]
        weighted_points = 0.0
        category_available_weight = 0
        category_available_metrics = 0
        metric_results = []
        for key, settings in category_settings["metrics"].items():
            expected_metric_count += 1
            value = valid_number(metrics.get(key))
            points = _metric_points(value, settings)
            common = {
                "key": key,
                "label": settings["label"],
                "max_score": settings["weight"],
                "explanation": METRIC_EXPLANATIONS[key],
            }
            if points is None:
                metric_results.append({
                    **common, "value": None, "formatted_value": "N/A", "display_value": "N/A",
                    "score": None, "status": "unavailable", "availability": "unavailable",
                    "available": False, "reference": "Excluded from score normalization",
                })
                continue
            quality = points / settings["weight"]
            weighted_points += points
            category_available_weight += settings["weight"]
            available_weight += settings["weight"]
            category_available_metrics += 1
            available_metric_count += 1
            display_value = format_metric(key, value)
            metric_results.append({
                **common, "value": value, "formatted_value": display_value,
                "display_value": display_value, "score": round(points, 1),
                "status": score_label(round(quality * 100)).lower(),
                "availability": "available", "available": True,
                "reference": _reference(settings),
                **({"calculation_method": CALCULATION_METHODS[key]} if key in CALCULATION_METHODS else {}),
            })

        expected_in_category = len(category_settings["metrics"])
        category_coverage = category_available_metrics / expected_in_category if expected_in_category else 0
        if category_available_weight:
            available_categories += 1
            normalized = max(0.0, min(float(max_score), weighted_points / category_available_weight * max_score))
            normalized_category_points += normalized
            available_category_weight += max_score
            categories[category] = {
                "score": round(normalized, 1), "max_score": max_score,
                "label": score_label(round(normalized / max_score * 100)),
                "available_weight": category_available_weight,
                "available_metrics": category_available_metrics,
                "expected_metrics": expected_in_category,
                "coverage": round(category_coverage, 4),
                "metrics": metric_results, "details": metric_results,
                "normalization_note": (
                    f"Category score normalized using {category_available_metrics} "
                    f"of {expected_in_category} available metrics."
                    if category_available_metrics < expected_in_category else None
                ),
            }
        else:
            categories[category] = {
                "score": None, "max_score": max_score, "label": "Unavailable",
                "available_weight": 0, "available_metrics": 0,
                "expected_metrics": expected_in_category, "coverage": 0.0,
                "metrics": metric_results, "details": metric_results,
                "normalization_note": "No category metrics were available; this category was excluded from score normalization.",
            }

    coverage_percentage = round(available_weight)
    overall_coverage = available_metric_count / expected_metric_count if expected_metric_count else 0
    confidence = "high" if coverage_percentage >= 80 else "moderate" if coverage_percentage >= 60 else "low" if coverage_percentage else "none"
    coverage_result = {
        "percentage": coverage_percentage, "ratio": round(overall_coverage, 4),
        "available_weight": available_weight, "total_weight": 100,
        "available_metrics": available_metric_count, "expected_metrics": expected_metric_count,
        "confidence": confidence,
    }
    common_result = {
        "coverage": coverage_result, "available_metrics": available_metric_count,
        "expected_metrics": expected_metric_count, "categories": categories,
        "version": SCORE_VERSION,
    }
    if coverage_percentage < MINIMUM_COVERAGE_PERCENT or available_categories < MINIMUM_CATEGORIES:
        return {
            **common_result, "status": "unavailable", "score": None, "label": "Unavailable",
            "reason_code": "insufficient_financial_data",
            "message": "The financial-data provider did not return enough reliable information.",
        }

    total = max(0.0, min(100.0, normalized_category_points / available_category_weight * 100))
    total = round(total, 1)
    status = "available" if coverage_percentage == 100 else "partial"
    return {
        **common_result, "status": status, "score": total, "label": score_label(round(total)),
        "message": "Score is based on limited available financial data." if status == "partial" else None,
    }
